name: pr-assign
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# TODO
## Make sure if pull request auther is removed from the 'reviewers' list, if present (HTTP code 422 - Review cannot be requested from pull request author.)

jobs:
  log:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      PULL_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v4
      - name: Add myself as a reviewer
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/Flutter-Global/auto-assign-actions/pulls/$PULL_NUMBER/requested_reviewers" \
            -d '{"reviewers":["snape-sbg"]}'