name: toggle
on:
  workflow_dispatch:

permissions:
  actions: write

jobs:
  log:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: toggle-state
          key: toggle-key
      - name: Print file content
        run: |
          FILE=toggle-state
          if [ -f "$FILE" ]; then
            cat "$FILE"
          else
            echo "$FILE does not exist"
            echo "Hello, World!" > $FILE
          fi
      - name: Toggle file content
        run: |
          FILE=toggle-state
          if [ -f "$FILE" ]; then
            content=$(cat "$FILE")
            if [ "$content" = "true" ]; then
              echo "false" > "$FILE"
            else
              echo "true" > "$FILE"
            fi
          fi
      - name: Clear cache
        uses: actions/github-script@v6
        with:
          script: |
            console.log("About to clear")
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              console.log(cache)
              github.rest.actions.deleteActionsCacheById({
                owner: context.repo.owner,
                repo: context.repo.repo,
                cache_id: cache.id,
              })
            }
            console.log("Clear completed")
      